

* 2021-11-08 - change non-concurrent collection

Friflo.Json.Fliox.Hub.Client.SyncTasksException : Internal InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Friflo.Json.Fliox.Hub.Host.FlioxHub.UpdateRequestStats(String database, SyncRequest syncRequest, MessageContext messageContext) in G:\_dev\Unity\HoverLab\Assets\Friflo\Json\Fliox.Hub\Host\FlioxHub.cs:line 221
   at Friflo.Json.Fliox.Hub.Host.FlioxHub.ExecuteSync(SyncRequest syncRequest, MessageContext messageContext) in G:\_dev\Unity\HoverLab\Assets\Friflo\Json\Fliox.Hub\Host\FlioxHub.cs:line 176
   at Friflo.Json.Fliox.Hub.Client.FlioxClient.ExecuteSync(SyncRequest syncRequest, MessageContext messageContext) in G:\_dev\Unity\HoverLab\Assets\Friflo\Json\Fliox.Hub\Client\FlioxClient.cs:line 334 --- Internal End
   at Friflo.Json.Fliox.Hub.Client.FlioxClient.SyncTasks() in G:\_dev\Unity\HoverLab\Assets\Friflo\Json\Fliox.Hub\Client\FlioxClient.cs:line 90
   at Friflo.Json.Tests.Common.UnitTest.Fliox.Client.Happy.TestHappy.<>c__DisplayClass13_0.<<ReadLoop>b__0>d.MoveNext() in G:\_dev\Unity\HoverLab\Assets\Friflo\Json.Tests\Common\UnitTest\Fliox\Client\Happy\Test-Concurrency.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at Friflo.Json.Tests.Common.UnitTest.Fliox.Client.Happy.TestHappy.ConcurrentAccess(FlioxHub hub, Int32 readerCount, Int32 writerCount, Int32 requestCount, Boolean singleEntity) in G:\_dev\Unity\HoverLab\Assets\Friflo\Json.Tests\Common\UnitTest\Fliox\Client\Happy\Test-Concurrency.cs:line 93
   at Friflo.Json.Tests.Common.UnitTest.Fliox.Client.Happy.TestHappy.<>c.<<TestConcurrentFileAccessSync>b__11_0>d.MoveNext() in G:\_dev\Unity\HoverLab\Assets\Friflo\Json.Tests\Common\UnitTest\Fliox\Client\Happy\Test-Concurrency.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at Friflo.Json.Fliox.Hub.Threading.SingleThreadSynchronizationContext.Run(Func`1 func) in G:\_dev\Unity\HoverLab\Assets\Friflo\Json\Fliox.Hub\Threading\SingleThreadSynchronizationContext.cs:line 45
   at Friflo.Json.Tests.Common.UnitTest.Fliox.Client.Happy.TestHappy.TestConcurrentFileAccessSync() in G:\_dev\Unity\HoverLab\Assets\Friflo\Json.Tests\Common\UnitTest\Fliox\Client\Happy\Test-Concurrency.cs:line 32
